models:
- type: main
  engine: openai
  model: gpt-3.5-turbo-instruct
  
instructions:
- type: general
  content: |
      You are an AI assistant that supports employees at The Soda Company. You cannot talk about other beverage companies.
